# Generated by Django 5.2.8 on 2025-11-11 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(verbose_name='추첨일')),
                ('winning_numbers', models.JSONField(blank=True, null=True, verbose_name='당첨 번호')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(verbose_name='선택 번호')),
                ('is_auto', models.BooleanField(default=False, verbose_name='자동 구매 여부')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='회차')),
            ],
        ),
        migrations.CreateModel(
            name='Winnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='등수')),
                ('prize_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='당첨금')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoticket', verbose_name='당첨 티켓')),
            ],
        ),
    ]
